from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from utils.rag import (
    recommend_recipes,
    required_ingredients,
    cooking_instructions,
    determine_intent
)

class Message(BaseModel):
    role: str = Field(..., example="user", description="Role of the sender: user or admin")
    content: str = Field(...,  example="I have ingredients A, B, C. What can I cook with them?",
                         description="Content of the message")

class ChatRequest(BaseModel):
    history: list[Message] = Field(..., description="Message history of the user, the last message is the new request of user")

class ChatResponse(BaseModel):
    response: str = Field(..., description="Generated by RAG-system response")
    intent: str = Field(..., description="Intent of the message")

app = FastAPI(
    title="Recipe RAG Assistant API",
    description="RESTful API for retrival of receipts, using Qdrant and Azure OpenAI"
)

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    if not request.history:
        raise HTTPException(status_code=400, detail="No history provided")

    latest_user_message = next((msg.content for msg in reversed(request.history) if msg.role == 'user'), None)

    if not latest_user_message:
        raise HTTPException(status_code=400, detail="No message provided")

    try:
        intent = determine_intent(latest_user_message)

        rag_response = ""

        if intent == "recommend_recipes":
            rag_response = recommend_recipes(latest_user_message)

        elif intent == "cooking_instructions":
            dish_title = latest_user_message.strip()
            rag_response = cooking_instructions(dish_title)

        elif intent == "required_ingredients":
            dish_title = latest_user_message.strip()
            rag_response = required_ingredients(dish_title)

        else:
            rag_response = "I couldn't understand your request"
    except Exception as ex:
        print(f"RAG-pipeline error: {ex}")
        raise HTTPException(status_code=500, detail=f"On server RAG error: {str(ex)}")

    return ChatResponse(response=rag_response, intent=intent)

